name: Python CI

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    # Add step to install dependencies
    - name: Install dependencies
      run: python -m pip install --upgrade pip
    - name: Test with pytest
      run: pip install pytest
          pytest test_bad_code.py





  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install Flake8
      run: pip install flake8
    
    # Complete the lint job configuration
